DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	memId VARCHAR(10) PRIMARY KEY,
	memPw VARCHAR(10),
	memMail VARCHAR(20),
	memPhone1 VARCHAR(3),
	memPhone2 VARCHAR(4),
	memPhone3 VARCHAR(4)
);

SELECT * FROM MEMBER;

COMMIT