SELECT * FROM TAB;

DROP TABLE REGISTER;

CREATE TABLE REGISTER (
	ID    VARCHAR(20) NOT NULL,
	PWD   VARCHAR(20) NOT NULL,
	NAME  VARCHAR(20) DEFAULT NULL,
	EMAIL VARCHAR(20) DEFAULT NULL,
	PHONE VARCHAR(20) DEFAULT NULL,
	-- PRIMARY KEY ID
	CONSTRAINT REGISTER_PK PRIMARY KEY(ID)
);

-- INSERT INTO REGISTER 데이터 3개 넣기
INSERT ALL
INTO REGISTER VALUES('a', 'a', 'a', 'a@naver.com', '010-0000-0000')
INTO REGISTER VALUES('b', 'b', 'b', 'b@naver.com', '010-0000-0000')
INTO REGISTER VALUES('c', 'c', 'c', 'c@naver.com', '010-0000-0000')
SELECT * FROM DUAL;

SELECT * FROM REGISTER;

COMMIT
